language: docker

install:
- mvn compile

script:
- echo "Building Application"
- mvn package
- echo "Building Docker Container"
- printenv
- docker build -t  .

after_script:
- echo "Pushing Container to Registry"
- echo "docker push"

before_deploy:
- echo "PreDeployment Version"
- kubectl version
deploy:
- kubectl version
