language: docker

# install:
# - mvn compile

script:
- echo "Building Application"
- mvn package
- echo "Building Docker Container"
- printenv
- docker build --label CSV_URL="${GIT_URL}" --label COMMIT="${GIT_COMMIT}" -t "localhost:5001/docker/${JOB_NAME}:${BUILD_ID}" .
- docker tag "localhost:5001/docker/${JOB_NAME}:${BUILD_ID}" "localhost:5001/docker/${JOB_NAME}:latest"
- echo "Pushing Container to Registry"
- docker push "localhost:5001/docker/${JOB_NAME}:${BUILD_ID}"
- docker push "localhost:5001/docker/${JOB_NAME}:latest"

before_deploy:
- echo "PreDeployment Version"
- kubectl version
deploy:
- echo "kubectl apply"
- kubectl apply -f ./java-application.yml
- echo "Updating image in deployment to localhost/docker/${JOB_NAME}:${BUILD_ID}"
- kubectl set image deployment/my-java-app localhost/docker/${JOB_NAME}:${BUILD_ID}
- echo "Rolling out update"
- kubectl rollout status deployment/my-java-app
