apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: team-1
  name: my-java-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: my-java-app
    spec:
      containers:
      - name: my-java-app
        image: localhost:5001/docker/myproject:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          # Can't have a host port because we have one host :)
          # hostPort: 8090
        volumeMounts:
        - name: config-volume
          mountPath: /props
      volumes:
      - name: config-volume
        configMap:
          name: my-java-app-configmap
          items:
          - key: message-of-the-day
            path: my-java-configuration.properties
---
apiVersion: v1
kind: Service
metadata:
  name: my-java-app
  namespace: team-1
spec:
  selector:
    name: my-java-app
  ports:
  - name: message-of-the-day
    port: 9090
    targetPort: 8080
