kind: Namespace
apiVersion: v1
metadata:
  name: team-1
  labels:
    name: team-1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: team-1
  name: my-java-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: my-java-app
    spec:
      containers:
      - name: my-java-app
        image: localhost:5001/docker/myproject:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - key: message-of-the-day
          valueFrom:
            configMapKeyRef:
              name: my-java-app-configmap
              key: message-of-the-day
          # Can't have a host port because we have one host :)
          # hostPort: 8090
